FROM node:16.14.2

ARG SENTRY_AUTH_TOKEN=''
ARG SENTRY_DSN=''
ARG FIREBASE_API_KEY=''
ARG FIREBASE_AUTH_DOMAIN=''
ARG FIREBASE_PROJECT_ID=''
ARG FIREBASE_STORAGE_BUCKET=''
ARG FIREBASE_MESSENGER_SENDER_ID=''
ARG FIREBASE_APP_ID=''
ARG FIREBASE_MEASUREMENT_ID=''

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . ./

RUN npm ci

RUN SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_DSN=$SENTRY_DSN \
  FIREBASE_API_KEY=$FIREBASE_API_KEY FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN \
  FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
  FIREBASE_MESSENGER_SENDER_ID=$FIREBASE_MESSENGER_SENDER_ID FIREBASE_APP_ID=$FIREBASE_APP_ID \
  FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID APP_ENV=production npm run build

EXPOSE 3000
ENTRYPOINT ["npm", "run", "start"]
