name: pr-merge tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - run: npm ci

      - name: Lint code
        run: npm run lint

      - run: CI=true APP_ENV=development npm run build
